Repository atar-axis/xpadneo, pull requests merged in 2020-07, with the labels that each got.

#206 dkms: Eliminate bash scripting from udev rules
  hid-xpadneo/dkms.post_install
  hid-xpadneo/dkms.post_remove
  hid-xpadneo/src/etc-modprobe.d/xpadneo.conf
  hid-xpadneo/src/etc-udev-rules.d/98-xpadneo.rules
  hid-xpadneo/src/udev_rules/99-xpadneo.rules
Labels: 0 | type: enhancement

#216 dmks, installer: Move etc sources one level up
  hid-xpadneo/etc-modprobe.d/xpadneo.conf
  hid-xpadneo/etc-udev-rules.d/98-xpadneo.rules
Labels: 0 | type: bug

#213 Add support for XBE2 (Unknown mode)
  docs/README.md
  docs/descriptors/xbe2_unknown.md
  hid-xpadneo/src/hid-xpadneo.c
Labels: 0 | type: hardware support, 1 | state: ready to merge, 1 | state: testing solution, 1 | state: waiting for reporter feedback

#222 Handle missing, duplicate and unrelated files in `/etc/modprobe.d`
  configure.sh
Labels: 0 | type: bug

#230 xpadneo, udev: Work around libinput using the controller as touchpad
  hid-xpadneo/etc-udev-rules.d/98-xpadneo.rules
Labels: 0 | type: third party bug, 1 | state: dirty fix, 1 | state: testing solution

#229 Fix 8BitDo controllers layout and button mapping
  docs/README.md
  docs/descriptors/8bitso_sn30_windows.md
  hid-xpadneo/src/hid-xpadneo.c
Labels: 0 | type: bug, 0 | type: enhancement, 0 | type: hardware support, 1 | state: testing solution

#232 Rework dead zone handling
  configure.sh
  docs/CONFIGURATION.md
  docs/README.md
  hid-xpadneo/src/hid-xpadneo.c
Labels: 0 | type: enhancement, 1 | state: testing solution
